#!/usr/bin/env bash

set -o pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Backup current database state for devint environment
##?
##? Usage:
##?    backup
docs::parse "$@"

/bin/bash -c "${DEVINT_HOME}/backup.sh"
