#!/usr/bin/env bash

set -o pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Restores database from latest backup for devint environment
##?
##? Usage:
##?    restore
docs::parse "$@"

/bin/bash -c "${DEVINT_HOME}/restore.sh"
