#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Add intellij Code Style symlink (since it's not synced via JetBrains Toolbox)
#?? 1.0.0
##?
##? Usage:
##?   add_code_styles
docs::parse "$@"

preferences_dir="$HOME/.config/JetBrains"
intellij_version=$(ls "$preferences_dir" | grep 'IntelliJIdea' | sort -r | head -n 1)
intellij_code_styles_folder="$preferences_dir/$intellij_version/codestyles"

rm -rf "$intellij_code_styles_folder"
ln -s -i "$DOTFILES_PATH/editors/intellij/Code Style/" "$intellij_code_styles_folder"

echo "Applied to path: $intellij_code_styles_folder"
echo "Done for $intellij_version!"